package com.example.agentic.domain;

public enum RunStatus {
    CREATED, ANALYZING, AWAITING_CLARIFICATION, PLANNING, AWAITING_PLAN_APPROVAL,
    EXECUTING, AWAITING_REVIEW, COMPLETED, REJECTED, FAILED, CANCELLED
}