package com.example.agentic.agents.dto;

import com.example.agentic.common.InvalidOutputException;
import com.example.agentic.llm.Validatable;
import java.util.List;

public record EngineeringSummary(String implementationPlan, String rationale, List<String> risksAndTradeoffs,
                                 String validationApproach, List<String> assumptions,
                                 List<String> limitations) implements Validatable {

    public EngineeringSummary {
        risksAndTradeoffs = Lists.nn(risksAndTradeoffs);
        assumptions = Lists.nn(assumptions);
        limitations = Lists.nn(limitations);
    }

    @Override
    public void validate() {
        if (implementationPlan == null || implementationPlan.isBlank())
            throw new InvalidOutputException("field 'implementationPlan' is required");
        if (validationApproach == null || validationApproach.isBlank())
            throw new InvalidOutputException("field 'validationApproach' is required");
    }

    /** The artifact index is generated by code from what is actually stored, never by the model. */
    public String toMarkdown(String artifactIndex) {
        StringBuilder sb = new StringBuilder("# Engineering summary\n\n## Implementation plan\n")
                .append(implementationPlan).append("\n\n## Rationale\n").append(rationale)
                .append("\n\n## Generated artifacts\n").append(artifactIndex)
                .append("\n## Risks and trade-offs\n");
        risksAndTradeoffs.forEach(r -> sb.append("- ").append(r).append("\n"));
        sb.append("\n## Validation approach\n").append(validationApproach).append("\n\n## Assumptions\n");
        assumptions.forEach(a -> sb.append("- ").append(a).append("\n"));
        sb.append("\n## Limitations\n");
        limitations.forEach(l -> sb.append("- ").append(l).append("\n"));
        return sb.toString();
    }
}